### ISSUE TITLE
SPI Flash invalid H7B3

### ISSUE THREAD

**Issue by UiARawi** [sirius506/DoomPlayer#1]
Any clue why i get the error?

**Comment by sirius506** [comment]
Initially, nothing is written on the SPI flash and you'll get 'SPI Flash invalid' message on the initial screen.  You'll also see 'Game not written' message on the grey button (instead of green).

In this case, you need to select one of GAME WAD file shown as orange button.
Please refer [Game copy section of wiki page.](https://github.com/sirius506/DoomPlayer/wiki/Screens)

If you don't see any orange button, it means you don't have any valid WAD file on the SD card. Get or buy valid WAD file and [copy it on the SD card](https://github.com/sirius506/DoomPlayer/wiki/SD-Card#sd-card).

**Comment by UiARawi** [comment]
Okay, this makes sense. 
Where to get/buy WAD files?

**Comment by sirius506** [comment]
As described in [this page](https://github.com/sirius506/DoomPlayer/wiki/SD-Card#gamedata), you can download share ware version from [this link](https://doomwiki.org/wiki/DOOM1.WAD).

You can purchase Commercial version of games at [Steam Store](https://store.steampowered.com). Try to search 'DOOM 1993' and/or 'DOOM classic' at the store. Note that those games are sold as package. You need to install it on the Window environment and try to find installed WAD file(s) on the disk.
Ref: https://steamcommunity.com/app/2300/discussions/0/3145179175823650475/

**Comment by sirius506** [comment]
No news is good news?
I assume your problem has solved and close this issue.

**Comment by UiARawi** [comment]
Sorry for late reply! Many things going on. 
The issue was solved when copied .wad file to SD.

Many thanks!
